{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1671", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1671/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1671/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1671/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/1671", "id": 1669527968, "node_id": "I_kwDOJKSTjM5jgvmg", "number": 1671, "title": "Data Ingestion doesn't work", "user": {"login": "Tejaswgupta", "id": 41832833, "node_id": "MDQ6VXNlcjQxODMyODMz", "avatar_url": "https://avatars.githubusercontent.com/u/41832833?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Tejaswgupta", "html_url": "https://github.com/Tejaswgupta", "followers_url": "https://api.github.com/users/Tejaswgupta/followers", "following_url": "https://api.github.com/users/Tejaswgupta/following{/other_user}", "gists_url": "https://api.github.com/users/Tejaswgupta/gists{/gist_id}", "starred_url": "https://api.github.com/users/Tejaswgupta/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Tejaswgupta/subscriptions", "organizations_url": "https://api.github.com/users/Tejaswgupta/orgs", "repos_url": "https://api.github.com/users/Tejaswgupta/repos", "events_url": "https://api.github.com/users/Tejaswgupta/events{/privacy}", "received_events_url": "https://api.github.com/users/Tejaswgupta/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 5272676246, "node_id": "LA_kwDOJKSTjM8AAAABOkanlg", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/help%20wanted", "name": "help wanted", "color": "008672", "default": true, "description": "Extra attention is needed"}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 21, "created_at": "2023-04-15T18:34:10Z", "updated_at": "2023-04-18T18:43:04Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### Duplicates\n\n- [X] I have searched the existing issues\n\n### Steps to reproduce \ud83d\udd79\n\nRunning `autogpt/data_ingestion.py` fails on stable , but i got it work by borrowing code from an open PR which is adding the following to the file:\r\n```\r\nimport sys\r\nfrom pathlib import Path\r\n\r\nsys.path.append(str(Path(__file__).resolve().parent.parent))\r\n```\r\n\r\nRunning: \r\n`python autogpt/data_ingestion.py --dir auto_gpt_workspace` \r\nReturns:\r\n`\r\nUsing memory of type: LocalCache\r\nDirectory 'auto_gpt_workspace' ingested successfully.\r\n`\r\n\r\nI also tried inserting the contents of older `auto-got.json` into the blank version, but it still got overridden.\r\n\n\n### Current behavior \ud83d\ude2f\n\n`log-ingestion.txt` also remains empty after this and the script starts from the very beginning that is running google search.\n\n### Expected behavior \ud83e\udd14\n\nIt should load previous from memory and start from there? \n\n### Your prompt \ud83d\udcdd\n\n_No response_", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1671/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1671/timeline", "performed_via_github_app": null, "state_reason": null}