{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/319", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/319/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/319/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/319/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/319", "id": 1657512946, "node_id": "I_kwDOJKSTjM5iy6Py", "number": 319, "title": "Failed to parse AI output, attempting to fix.  If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.", "user": {"login": "yunga1", "id": 130071011, "node_id": "U_kgDOB8C54w", "avatar_url": "https://avatars.githubusercontent.com/u/130071011?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yunga1", "html_url": "https://github.com/yunga1", "followers_url": "https://api.github.com/users/yunga1/followers", "following_url": "https://api.github.com/users/yunga1/following{/other_user}", "gists_url": "https://api.github.com/users/yunga1/gists{/gist_id}", "starred_url": "https://api.github.com/users/yunga1/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yunga1/subscriptions", "organizations_url": "https://api.github.com/users/yunga1/orgs", "repos_url": "https://api.github.com/users/yunga1/repos", "events_url": "https://api.github.com/users/yunga1/events{/privacy}", "received_events_url": "https://api.github.com/users/yunga1/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 50, "created_at": "2023-04-06T14:16:49Z", "updated_at": "2023-04-27T09:36:59Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### Duplicates\n\n- [X] I have searched the existing issues\n\n### Steps to reproduce \ud83d\udd79\n\nUpgraded to latest version with Pinecone. Prompts that worked great yesterday now break constantly. Throwing the error:\r\n\r\nFailed to parse AI output, attempting to fix.\r\n If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.\r\n \r\n I'm using GPT3.5.\n\n### Current behavior \ud83d\ude2f\n\n_No response_\n\n### Expected behavior \ud83e\udd14\n\n_No response_\n\n### Your prompt \ud83d\udcdd\n\ndesignAI\r\n\r\nAn AI created to help with design direction for a SaaS company\r\n\r\nResearch 2023 graphic design trends\r\n\r\nTake 10 of the trends, and list them with description in a csv file", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/319/reactions", "total_count": 7, "+1": 7, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/319/timeline", "performed_via_github_app": null, "state_reason": null}