{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3043", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3043/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3043/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3043/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/3043", "id": 1680101717, "node_id": "I_kwDOJKSTjM5kJFFV", "number": 3043, "title": " Line 45 configurator.py CFG.set_speak_mode(True) set True as default", "user": {"login": "PaulShroom", "id": 131564167, "node_id": "U_kgDOB9eChw", "avatar_url": "https://avatars.githubusercontent.com/u/131564167?v=4", "gravatar_id": "", "url": "https://api.github.com/users/PaulShroom", "html_url": "https://github.com/PaulShroom", "followers_url": "https://api.github.com/users/PaulShroom/followers", "following_url": "https://api.github.com/users/PaulShroom/following{/other_user}", "gists_url": "https://api.github.com/users/PaulShroom/gists{/gist_id}", "starred_url": "https://api.github.com/users/PaulShroom/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/PaulShroom/subscriptions", "organizations_url": "https://api.github.com/users/PaulShroom/orgs", "repos_url": "https://api.github.com/users/PaulShroom/repos", "events_url": "https://api.github.com/users/PaulShroom/events{/privacy}", "received_events_url": "https://api.github.com/users/PaulShroom/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 5347563882, "node_id": "LA_kwDOJKSTjM8AAAABPr1Zag", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/setup", "name": "setup", "color": "E1BC6F", "default": false, "description": "Issues with getting Auto-GPT setup on local machines"}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2023-04-23T17:23:13Z", "updated_at": "2023-04-23T20:43:53Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### \u26a0\ufe0f Search for existing issues first \u26a0\ufe0f\n\n- [X] I have searched the existing issues, and there is no existing issue for my problem\n\n### Which Operating System are you using?\n\nWindows\n\n### Which version of Auto-GPT are you using?\n\nStable (branch)\n\n### GPT-3 or GPT-4?\n\nGPT-3.5\n\n### Steps to reproduce \ud83d\udd79\n\n Line 45 configurator.py CFG.set_speak_mode(False) set \"True\" as default on first use. As I had no tts and this would have been good to have on to stop me from going crazy thinking something was wrong with my installation.\n\n### Current behavior \ud83d\ude2f\n\nno tts Line 45 configurator.py CFG.set_speak_mode(False)\n\n### Expected behavior \ud83e\udd14\n\nLine 45 configurator.py CFG.set_speak_mode(True) tts on\r\n\n\n### Your prompt \ud83d\udcdd\n\n```yaml\r\n# Paste your prompt here\r\n```\r\n\n\n### Your Logs \ud83d\udcd2\n\n```log\r\n<insert your logs here>\r\n```\r\n", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3043/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3043/timeline", "performed_via_github_app": null, "state_reason": null}