{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3648", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3648/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3648/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3648/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/3648", "id": 1691545156, "node_id": "I_kwDOJKSTjM5k0u5E", "number": 3648, "title": "Execute_python_file error while using imports in executed code", "user": {"login": "bfalans", "id": 49377421, "node_id": "MDQ6VXNlcjQ5Mzc3NDIx", "avatar_url": "https://avatars.githubusercontent.com/u/49377421?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bfalans", "html_url": "https://github.com/bfalans", "followers_url": "https://api.github.com/users/bfalans/followers", "following_url": "https://api.github.com/users/bfalans/following{/other_user}", "gists_url": "https://api.github.com/users/bfalans/gists{/gist_id}", "starred_url": "https://api.github.com/users/bfalans/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bfalans/subscriptions", "organizations_url": "https://api.github.com/users/bfalans/orgs", "repos_url": "https://api.github.com/users/bfalans/repos", "events_url": "https://api.github.com/users/bfalans/events{/privacy}", "received_events_url": "https://api.github.com/users/bfalans/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 5405678652, "node_id": "LA_kwDOJKSTjM8AAAABQjQcPA", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/function:%20run%20code", "name": "function: run code", "color": "61F3B2", "default": false, "description": ""}, {"id": 5405679248, "node_id": "LA_kwDOJKSTjM8AAAABQjQekA", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/docker", "name": "docker", "color": "5152EA", "default": false, "description": ""}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2023-05-01T23:18:35Z", "updated_at": "2023-05-02T22:18:21Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### \u26a0\ufe0f Search for existing issues first \u26a0\ufe0f\n\n- [X] I have searched the existing issues, and there is no existing issue for my problem\n\n### Which Operating System are you using?\n\nWindows\n\n### Which version of Auto-GPT are you using?\n\nLatest Release\n\n### GPT-3 or GPT-4?\n\nGPT-3.5\n\n### Steps to reproduce \ud83d\udd79\n\nCreate python code with imports.\r\nLet autogpt execute the code\n\n### Current behavior \ud83d\ude2f\n\nImports are not recognized during execute_python_file (maybe running in a docker container with no python package imports) resulting in a loop around the execute file and very strange python code files\n\n### Expected behavior \ud83e\udd14\n\nExecuted file runs in docker container without issues\n\n### Your prompt \ud83d\udcdd\n\n```yaml\r\n# not applicable\r\n```\r\n\n\n### Your Logs \ud83d\udcd2\n\n```log\r\nNo log available\r\n```\r\n", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3648/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3648/timeline", "performed_via_github_app": null, "state_reason": null}