{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1134", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1134/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1134/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1134/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/1134", "id": 1666654174, "node_id": "I_kwDOJKSTjM5jVx_e", "number": 1134, "title": "Main.py ERROR when launching application ", "user": {"login": "JulsdL", "id": 64731066, "node_id": "MDQ6VXNlcjY0NzMxMDY2", "avatar_url": "https://avatars.githubusercontent.com/u/64731066?v=4", "gravatar_id": "", "url": "https://api.github.com/users/JulsdL", "html_url": "https://github.com/JulsdL", "followers_url": "https://api.github.com/users/JulsdL/followers", "following_url": "https://api.github.com/users/JulsdL/following{/other_user}", "gists_url": "https://api.github.com/users/JulsdL/gists{/gist_id}", "starred_url": "https://api.github.com/users/JulsdL/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/JulsdL/subscriptions", "organizations_url": "https://api.github.com/users/JulsdL/orgs", "repos_url": "https://api.github.com/users/JulsdL/repos", "events_url": "https://api.github.com/users/JulsdL/events{/privacy}", "received_events_url": "https://api.github.com/users/JulsdL/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2023-04-13T15:30:01Z", "updated_at": "2023-04-13T16:10:56Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### Duplicates\n\n- [X] I have searched the existing issues\n\n### Steps to reproduce \ud83d\udd79\n\nIn .env set TEMPERATURE to a float -> 0.2\r\nLaunch python scripts/main.py\r\n\r\n\r\n\n\n### Current behavior \ud83d\ude2f\n\nApplication crashes\r\n\r\n![Auto-GPT temperature error](https://user-images.githubusercontent.com/64731066/231808326-f1cdab09-919b-432c-aef7-1b70ae494be5.jpg)\n\n### Expected behavior \ud83e\udd14\n\nmain.py should launch Auto-GPT in the terminal with this message:\r\nWelcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.\r\nName your AI:  For example, 'Entrepreneur-GPT'\r\nAI Name:\r\n\r\nRESOLUTION: \r\nIn file config.py, line 47, replace\r\nself.temperature = **int**(os.getenv(\"TEMPERATURE\", \"1\"))\r\nby\r\nself.temperature = **float**(os.getenv(\"TEMPERATURE\", \"1\"))\r\n\n\n### Your prompt \ud83d\udcdd\n\n```yaml\r\n# Paste your prompt here\r\n```\r\n", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1134/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1134/timeline", "performed_via_github_app": null, "state_reason": null}