{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1189", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1189/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1189/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1189/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/1189", "id": 1667117533, "node_id": "I_kwDOJKSTjM5jXjHd", "number": 1189, "title": "RuntimeError: Failed to get response after 5 retries", "user": {"login": "luckyvictor", "id": 16015693, "node_id": "MDQ6VXNlcjE2MDE1Njkz", "avatar_url": "https://avatars.githubusercontent.com/u/16015693?v=4", "gravatar_id": "", "url": "https://api.github.com/users/luckyvictor", "html_url": "https://github.com/luckyvictor", "followers_url": "https://api.github.com/users/luckyvictor/followers", "following_url": "https://api.github.com/users/luckyvictor/following{/other_user}", "gists_url": "https://api.github.com/users/luckyvictor/gists{/gist_id}", "starred_url": "https://api.github.com/users/luckyvictor/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/luckyvictor/subscriptions", "organizations_url": "https://api.github.com/users/luckyvictor/orgs", "repos_url": "https://api.github.com/users/luckyvictor/repos", "events_url": "https://api.github.com/users/luckyvictor/events{/privacy}", "received_events_url": "https://api.github.com/users/luckyvictor/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 5409115183, "node_id": "LA_kwDOJKSTjM8AAAABQmiMLw", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/API%20access", "name": "API access", "color": "C5A39D", "default": false, "description": "Trouble with connecting to the API"}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 18, "created_at": "2023-04-13T20:58:32Z", "updated_at": "2023-04-19T15:54:32Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### Duplicates\n\n- [X] I have searched the existing issues\n\n### Steps to reproduce \ud83d\udd79\n\nI am on Mac.\r\n\r\nNo problem with the installation process, very smooth. I followed the instructions and input my openai api key as well as pinecone api key and region code.\r\n\r\nI managed to start the agent and gone as far as entering the 5 goals.\r\n\r\nIt gave me a warning of no auto-gpt.json, believe it is not a big deal.\r\n\r\nHowever after a minute of waiting, it reports\r\n\r\nRuntimeError: Failed to get response after 5 retries\r\n\r\nwhat is it and why do I get it?\n\n### Current behavior \ud83d\ude2f\n\n_No response_\n\n### Expected behavior \ud83e\udd14\n\n_No response_\n\n### Your prompt \ud83d\udcdd\n\n```yaml\r\n# Paste your prompt here\r\n```\r\n", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1189/reactions", "total_count": 12, "+1": 12, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1189/timeline", "performed_via_github_app": null, "state_reason": null}