{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2363", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2363/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2363/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2363/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/2363", "id": 1672820043, "node_id": "I_kwDOJKSTjM5jtTVL", "number": 2363, "title": "Crash on connection failure", "user": {"login": "SpaceTTAngel", "id": 131013386, "node_id": "U_kgDOB88bCg", "avatar_url": "https://avatars.githubusercontent.com/u/131013386?v=4", "gravatar_id": "", "url": "https://api.github.com/users/SpaceTTAngel", "html_url": "https://github.com/SpaceTTAngel", "followers_url": "https://api.github.com/users/SpaceTTAngel/followers", "following_url": "https://api.github.com/users/SpaceTTAngel/following{/other_user}", "gists_url": "https://api.github.com/users/SpaceTTAngel/gists{/gist_id}", "starred_url": "https://api.github.com/users/SpaceTTAngel/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/SpaceTTAngel/subscriptions", "organizations_url": "https://api.github.com/users/SpaceTTAngel/orgs", "repos_url": "https://api.github.com/users/SpaceTTAngel/repos", "events_url": "https://api.github.com/users/SpaceTTAngel/events{/privacy}", "received_events_url": "https://api.github.com/users/SpaceTTAngel/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 5272676193, "node_id": "LA_kwDOJKSTjM8AAAABOkanYQ", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": "Something isn't working"}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2023-04-18T10:26:24Z", "updated_at": "2023-04-19T01:40:08Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### \u26a0\ufe0f Search for existing issues first \u26a0\ufe0f\r\n\r\n- [X] I have searched the existing issues, and there is no existing issue for my problem\r\n\r\n### GPT-3 or GPT-4\r\n\r\n- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)\r\n\r\n### Steps to reproduce \ud83d\udd79\r\n\r\nWhile auto-gpt is running , with a task ongoing : \r\nNEXT ACTION:  COMMAND = browse_website ARGUMENTS = {.....\r\n\r\nI had for a moment a internet connection problem (maybe 1 minute without internet); I observed the following log:\r\n\r\n    raise error.APIConnectionError(openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\r\n\r\n\r\n\r\nI expected that auto-gpt continued to run also if for a moment internet connection was not available\r\n\r\n### Current behavior \ud83d\ude2f\r\n\r\nAuto-gpt crashes during the task ongoing : \r\n\r\nNEXT ACTION:  COMMAND = browse_website ARGUMENTS = {.....\r\n\r\nwith the following log:\r\n\r\n    raise error.APIConnectionError(openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\r\n\r\n\r\nif internet connection is not available\r\n\r\n### Expected behavior \ud83e\udd14\r\n\r\nAuto-gpt should not crash if internet connection is not available during website searching / browsing\r\n\r\n\r\n\r\n### Your prompt \ud83d\udcdd\r\n\r\n```yaml\r\n# Paste your prompt here\r\n```\r\n", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2363/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2363/timeline", "performed_via_github_app": null, "state_reason": null}