{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2634", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2634/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2634/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2634/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/2634", "id": 1676175779, "node_id": "I_kwDOJKSTjM5j6Gmj", "number": 2634, "title": "Docker execution - ModuleNotFoundError: No module named 'openapi_python_client'", "user": {"login": "70nyIT", "id": 12898752, "node_id": "MDQ6VXNlcjEyODk4NzUy", "avatar_url": "https://avatars.githubusercontent.com/u/12898752?v=4", "gravatar_id": "", "url": "https://api.github.com/users/70nyIT", "html_url": "https://github.com/70nyIT", "followers_url": "https://api.github.com/users/70nyIT/followers", "following_url": "https://api.github.com/users/70nyIT/following{/other_user}", "gists_url": "https://api.github.com/users/70nyIT/gists{/gist_id}", "starred_url": "https://api.github.com/users/70nyIT/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/70nyIT/subscriptions", "organizations_url": "https://api.github.com/users/70nyIT/orgs", "repos_url": "https://api.github.com/users/70nyIT/repos", "events_url": "https://api.github.com/users/70nyIT/events{/privacy}", "received_events_url": "https://api.github.com/users/70nyIT/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 5272676193, "node_id": "LA_kwDOJKSTjM8AAAABOkanYQ", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": "Something isn't working"}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2023-04-20T07:33:18Z", "updated_at": "2023-04-20T12:27:13Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### \u26a0\ufe0f Search for existing issues first \u26a0\ufe0f\n\n- [X] I have searched the existing issues, and there is no existing issue for my problem\n\n### Which Operating System are you using?\n\nDocker\n\n### GPT-3 or GPT-4?\n\nGPT-3.5\n\n### Steps to reproduce \ud83d\udd79\n\n* Clone the repository and `cd` in the `Auto-GPT` folder\r\n* Set up the .env files (example of mine below)\r\n* Run `docker build -t autogpt .` and `docker run -it --env-file=./.env -v $PWD/auto_gpt_workspace:/app/auto_gpt_workspace autogpt`\r\n\r\n`.env` file\r\n\r\n```\r\n################################################################################\r\n### AUTO-GPT - GENERAL SETTINGS\r\n################################################################################\r\nEXECUTE_LOCAL_COMMANDS=True\r\nBROWSE_CHUNK_MAX_LENGTH=8192\r\nBROWSE_SUMMARY_MAX_TOKEN=300\r\nAI_SETTINGS_FILE=ai_settings.yaml\r\n\r\n################################################################################\r\n### LLM PROVIDER\r\n################################################################################\r\n\r\n### OPENAI\r\nOPENAI_API_KEY=**{I-place-my-api-key-here}**\r\nTEMPERATURE=0\r\nUSE_AZURE=False\r\n\r\n\r\n################################################################################\r\n### LLM MODELS\r\n################################################################################\r\n\r\nSMART_LLM_MODEL=gpt-4\r\nFAST_LLM_MODEL=gpt-3.5-turbo\r\n\r\n### LLM MODEL SETTINGS\r\nFAST_TOKEN_LIMIT=4000\r\nSMART_TOKEN_LIMIT=8000\r\n\r\n################################################################################\r\n### MEMORY\r\n################################################################################\r\n\r\n### MEMORY_BACKEND - Memory backend type\r\nMEMORY_BACKEND=local\r\n\r\n### PINECONE\r\nPINECONE_API_KEY=your-pinecone-api-key\r\nPINECONE_ENV=your-pinecone-region\r\n\r\n### REDIS\r\nREDIS_HOST=localhost\r\nREDIS_PORT=6379\r\nREDIS_PASSWORD=\r\nWIPE_REDIS_ON_START=False\r\nMEMORY_INDEX=auto-gpt\r\n\r\n### WEAVIATE\r\nWEAVIATE_HOST=\"127.0.0.1\"\r\nWEAVIATE_PORT=8080\r\nWEAVIATE_PROTOCOL=\"http\"\r\nUSE_WEAVIATE_EMBEDDED=False\r\nWEAVIATE_EMBEDDED_PATH=\"/home/me/.local/share/weaviate\"\r\nWEAVIATE_USERNAME=\r\nWEAVIATE_PASSWORD=\r\nWEAVIATE_API_KEY=\r\nMEMORY_INDEX=AutoGpt\r\n\r\n### MILVUS\r\nMILVUS_ADDR=your-milvus-cluster-host-port\r\nMILVUS_COLLECTION=autogpt\r\n\r\n################################################################################\r\n### IMAGE GENERATION PROVIDER\r\n################################################################################\r\n\r\n### OPEN AI\r\nIMAGE_PROVIDER=dalle\r\n\r\n### HUGGINGFACE\r\nHUGGINGFACE_API_TOKEN=your-huggingface-api-token\r\n\r\n################################################################################\r\n### AUDIO TO TEXT PROVIDER\r\n################################################################################\r\n\r\n### HUGGINGFACE\r\nHUGGINGFACE_AUDIO_TO_TEXT_MODEL=facebook/wav2vec2-base-960h\r\n\r\n################################################################################\r\n### GIT Provider for repository actions\r\n################################################################################\r\n\r\n### GITHUB\r\nGITHUB_API_KEY=**{I-place-my-api-key-here}**\r\nGITHUB_USERNAME=70nyIT\r\n\r\n################################################################################\r\n### SEARCH PROVIDER\r\n################################################################################\r\n\r\n### GOOGLE\r\nGOOGLE_API_KEY=**{I-place-my-api-key-here}**\r\nCUSTOM_SEARCH_ENGINE_ID=**{I-place-my-search-enginge-id-here}**\r\n\r\n################################################################################\r\n### TTS PROVIDER\r\n################################################################################\r\n\r\n### MAC OS\r\nUSE_MAC_OS_TTS=False\r\n\r\n### STREAMELEMENTS\r\nUSE_BRIAN_TTS=False\r\n\r\n### ELEVENLABS\r\nELEVENLABS_API_KEY=your-elevenlabs-api-key\r\nELEVENLABS_VOICE_1_ID=your-voice-id-1\r\nELEVENLABS_VOICE_2_ID=your-voice-id-2\r\n\r\n################################################################################\r\n### TWITTER API \r\n################################################################################\r\n\r\nTW_CONSUMER_KEY=\r\nTW_CONSUMER_SECRET=\r\nTW_ACCESS_TOKEN=\r\nTW_ACCESS_TOKEN_SECRET=\r\n```\n\n### Current behavior \ud83d\ude2f\n\nThe build completes, but this error is shown when the `docker run` command is executed\r\n\r\n```\r\nWarning: The file 'AutoGpt.json' does not exist. Local memory would not be saved to a file.\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"/usr/local/lib/python3.10/runpy.py\", line 86, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/home/appuser/autogpt/__main__.py\", line 5, in <module>\r\n    autogpt.cli.main()\r\n  File \"/home/appuser/.local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"/home/appuser/.local/lib/python3.10/site-packages/click/core.py\", line 1055, in main\r\n    rv = self.invoke(ctx)\r\n  File \"/home/appuser/.local/lib/python3.10/site-packages/click/core.py\", line 1635, in invoke\r\n    rv = super().invoke(ctx)\r\n  File \"/home/appuser/.local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"/home/appuser/.local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\r\n    return __callback(*args, **kwargs)\r\n  File \"/home/appuser/.local/lib/python3.10/site-packages/click/decorators.py\", line 26, in new_func\r\n    return f(get_current_context(), *args, **kwargs)\r\n  File \"/home/appuser/autogpt/cli.py\", line 83, in main\r\n    from autogpt.plugins import scan_plugins\r\n  File \"/home/appuser/autogpt/plugins.py\", line 12, in <module>\r\n    import openapi_python_client\r\nModuleNotFoundError: No module named 'openapi_python_client'\r\n```\n\n### Expected behavior \ud83e\udd14\n\nShould launch correctly the Auto-GPT terminal, ready to create the first task.\n\n### Your prompt \ud83d\udcdd\n\n```yaml\r\n- does not apply -\r\n```\r\n\n\n### Your Logs \ud83d\udcd2\n\n```log\r\nWarning: The file 'AutoGpt.json' does not exist. Local memory would not be saved to a file.\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"/usr/local/lib/python3.10/runpy.py\", line 86, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/home/appuser/autogpt/__main__.py\", line 5, in <module>\r\n    autogpt.cli.main()\r\n  File \"/home/appuser/.local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"/home/appuser/.local/lib/python3.10/site-packages/click/core.py\", line 1055, in main\r\n    rv = self.invoke(ctx)\r\n  File \"/home/appuser/.local/lib/python3.10/site-packages/click/core.py\", line 1635, in invoke\r\n    rv = super().invoke(ctx)\r\n  File \"/home/appuser/.local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"/home/appuser/.local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\r\n    return __callback(*args, **kwargs)\r\n  File \"/home/appuser/.local/lib/python3.10/site-packages/click/decorators.py\", line 26, in new_func\r\n    return f(get_current_context(), *args, **kwargs)\r\n  File \"/home/appuser/autogpt/cli.py\", line 83, in main\r\n    from autogpt.plugins import scan_plugins\r\n  File \"/home/appuser/autogpt/plugins.py\", line 12, in <module>\r\n    import openapi_python_client\r\nModuleNotFoundError: No module named 'openapi_python_client'\r\n```\r\n", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2634/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2634/timeline", "performed_via_github_app": null, "state_reason": null}