{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2810", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2810/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2810/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2810/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/2810", "id": 1678529685, "node_id": "I_kwDOJKSTjM5kDFSV", "number": 2810, "title": "Speech Mode not working: ModuleNotFoundError: No module named 'AppKit'", "user": {"login": "andrewbaisden", "id": 5095486, "node_id": "MDQ6VXNlcjUwOTU0ODY=", "avatar_url": "https://avatars.githubusercontent.com/u/5095486?v=4", "gravatar_id": "", "url": "https://api.github.com/users/andrewbaisden", "html_url": "https://github.com/andrewbaisden", "followers_url": "https://api.github.com/users/andrewbaisden/followers", "following_url": "https://api.github.com/users/andrewbaisden/following{/other_user}", "gists_url": "https://api.github.com/users/andrewbaisden/gists{/gist_id}", "starred_url": "https://api.github.com/users/andrewbaisden/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/andrewbaisden/subscriptions", "organizations_url": "https://api.github.com/users/andrewbaisden/orgs", "repos_url": "https://api.github.com/users/andrewbaisden/repos", "events_url": "https://api.github.com/users/andrewbaisden/events{/privacy}", "received_events_url": "https://api.github.com/users/andrewbaisden/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2023-04-21T13:31:04Z", "updated_at": "2023-04-21T16:04:37Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "I have an M1 MacBook Pro and I get this error when I try to use Speech Mode:\r\n\r\n```shell\r\nTraceback (most recent call last):\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\r\n    self.run()\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 975, in run\r\n    self._target(*self._args, **self._kwargs)\r\n  File \"/Users/andrewbaisden/Desktop/autogpt-app/Auto-GPT/autogpt/speech/say.py\", line 33, in speak\r\n    success = VOICE_ENGINE.say(text, voice_index)\r\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Users/andrewbaisden/Desktop/autogpt-app/Auto-GPT/autogpt/speech/base.py\", line 33, in say\r\n    return self._speech(text, voice_index)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Users/andrewbaisden/Desktop/autogpt-app/Auto-GPT/autogpt/speech/gtts.py\", line 20, in _speech\r\n    playsound(\"speech.mp3\", True)\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/playsound.py\", line 55, in _playsoundOSX\r\n    from AppKit     import NSSound\r\nModuleNotFoundError: No module named 'AppKit'\r\n```\r\n\r\nI tried installing these packages and still had the same error.\r\n\r\n```shell\r\npip install pyobjc\r\n```\r\n\r\n```shell\r\npip install AppKit\r\n```\r\n\r\nI also get this error when trying to update the playsound package to 1.3.0. Only 1.2.2 will install all other versions fail https://pypi.org/project/playsound/#history\r\n\r\n```shell\r\nCollecting playsound==1.3.0\r\n  Using cached playsound-1.3.0.tar.gz (7.7 kB)\r\n  Installing build dependencies ... done\r\n  Getting requirements to build wheel ... error\r\n  error: subprocess-exited-with-error\r\n  \r\n  \u00d7 Getting requirements to build wheel did not run successfully.\r\n  \u2502 exit code: 1\r\n  \u2570\u2500> [29 lines of output]\r\n      Traceback (most recent call last):\r\n        File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 353, in <module>\r\n          main()\r\n        File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 335, in main\r\n          json_out['return_val'] = hook(**hook_input['kwargs'])\r\n                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n        File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 118, in get_requires_for_build_wheel\r\n          return hook(config_settings)\r\n                 ^^^^^^^^^^^^^^^^^^^^^\r\n        File \"/private/var/folders/z6/fx2tpl_x3mvgnbqqtfc3rzvh0000gn/T/pip-build-env-rxi4q83a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py\", line 341, in get_requires_for_build_wheel\r\n          return self._get_build_requires(config_settings, requirements=['wheel'])\r\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n        File \"/private/var/folders/z6/fx2tpl_x3mvgnbqqtfc3rzvh0000gn/T/pip-build-env-rxi4q83a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py\", line 323, in _get_build_requires\r\n          self.run_setup()\r\n        File \"/private/var/folders/z6/fx2tpl_x3mvgnbqqtfc3rzvh0000gn/T/pip-build-env-rxi4q83a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py\", line 488, in run_setup\r\n          self).run_setup(setup_script=setup_script)\r\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n        File \"/private/var/folders/z6/fx2tpl_x3mvgnbqqtfc3rzvh0000gn/T/pip-build-env-rxi4q83a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py\", line 338, in run_setup\r\n          exec(code, locals())\r\n        File \"<string>\", line 6, in <module>\r\n        File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py\", line 1262, in getsource\r\n          lines, lnum = getsourcelines(object)\r\n                        ^^^^^^^^^^^^^^^^^^^^^^\r\n        File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py\", line 1244, in getsourcelines\r\n          lines, lnum = findsource(object)\r\n                        ^^^^^^^^^^^^^^^^^^\r\n        File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py\", line 1081, in findsource\r\n          raise OSError('could not get source code')\r\n      OSError: could not get source code\r\n      [end of output]\r\n  \r\n  note: This error originates from a subprocess, and is likely not a problem with pip.\r\nerror: subprocess-exited-with-error\r\n\r\n\u00d7 Getting requirements to build wheel did not run successfully.\r\n\u2502 exit code: 1\r\n\u2570\u2500> See above for output.\r\n\r\nnote: This error originates from a subprocess, and is likely not a problem with pip.\r\n```\r\n\r\nThese issues are related:\r\n\r\n[OSError: Unable to load sound #856](https://github.com/Significant-Gravitas/Auto-GPT/issues/856)\r\n\r\n[In speak mode: ModuleNotFoundError: No module named 'gi' #1697](https://github.com/Significant-Gravitas/Auto-GPT/issues/1697)\r\n\r\n[--speak mode not working #483](https://github.com/Significant-Gravitas/Auto-GPT/discussions/483)\r\n\r\nThe Speech Mode worked in this previous build but not the latest one I have only been able to get the text mode to work.", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2810/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2810/timeline", "performed_via_github_app": null, "state_reason": null}