{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1697", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1697/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1697/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1697/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/1697", "id": 1669556548, "node_id": "I_kwDOJKSTjM5jg2lE", "number": 1697, "title": "In speak mode: ModuleNotFoundError: No module named 'gi'", "user": {"login": "yegors", "id": 817935, "node_id": "MDQ6VXNlcjgxNzkzNQ==", "avatar_url": "https://avatars.githubusercontent.com/u/817935?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yegors", "html_url": "https://github.com/yegors", "followers_url": "https://api.github.com/users/yegors/followers", "following_url": "https://api.github.com/users/yegors/following{/other_user}", "gists_url": "https://api.github.com/users/yegors/gists{/gist_id}", "starred_url": "https://api.github.com/users/yegors/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yegors/subscriptions", "organizations_url": "https://api.github.com/users/yegors/orgs", "repos_url": "https://api.github.com/users/yegors/repos", "events_url": "https://api.github.com/users/yegors/events{/privacy}", "received_events_url": "https://api.github.com/users/yegors/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 5272676246, "node_id": "LA_kwDOJKSTjM8AAAABOkanlg", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/help%20wanted", "name": "help wanted", "color": "008672", "default": true, "description": "Extra attention is needed"}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 13, "created_at": "2023-04-15T20:11:32Z", "updated_at": "2023-04-27T07:12:21Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### Duplicates\n\n- [X] I have searched the existing issues\n\n### Steps to reproduce \ud83d\udd79\n\n1. Install via vscode + devcontainer method (on WIndows), using stable branch\r\n2. Template .env with necessary API keys and ELEVENLABS voice IDs\r\n3. Start with --speak arg\r\n\r\nspeech.mpeg file is generated and saved to disk, but the below error occurs. \n\n### Current behavior \ud83d\ude2f\n\n```\r\nContinue (y/n): Exception in thread Thread-1:\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\r\n    self.run()\r\n  File \"/usr/local/lib/python3.8/threading.py\", line 870, in run\r\n    self._target(*self._args, **self._kwargs)\r\n  File \"/workspaces/Auto-GPT/autogpt/speak.py\", line 112, in speak\r\n    success = eleven_labs_speech(text, voice_index)\r\n  File \"/workspaces/Auto-GPT/autogpt/speak.py\", line 55, in eleven_labs_speech\r\n    playsound(\"speech.mpeg\", True)\r\n  File \"/home/vscode/.local/lib/python3.8/site-packages/playsound.py\", line 91, in _playsoundNix\r\n    import gi\r\nModuleNotFoundError: No module named 'gi'\r\n```\r\n\r\nBeyond saying `y`, all further interactions are impossible (program freezes). \n\n### Expected behavior \ud83e\udd14\n\n_No response_\n\n### Your prompt \ud83d\udcdd\n\nN/A", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1697/reactions", "total_count": 3, "+1": 3, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1697/timeline", "performed_via_github_app": null, "state_reason": null}